package HogIT;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Gabriel
 */
public class Poang extends javax.swing.JFrame {

    private final InfDB idb;

    /**
     * Creates new form Huvudfonster
     *
     * @throws oru.inf.InfException
     */
    public Poang() throws InfException {
        initComponents();

        idb = new InfDB("c:\\db\\hogdb(1).fdb");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Antal = new javax.swing.JTextField();
        genomför = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        genomför.setText("ok");
        genomför.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genomförActionPerformed(evt);
            }
        });

        jLabel1.setText("Poäng");

        jLabel2.setText("Elevhemsnamn:");

        jLabel3.setText("ge poäng eller dra av:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genomför)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hem, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(Antal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Antal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(genomför)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genomförActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genomförActionPerformed

        
        if(Validering.textFaltHarVarde(hem) && (Validering.isHeltal(Antal))){

            // Kod för att ge eller ta poäng
        try {      // skickar frågor till FDB
            String namn = hem.getText();
            String svar = idb.fetchSingle("SELECT ELEVHEMSNAMN from ELEVHEM where ELEVHEMSNAMN =" + "'" + namn + "'");
            String hamtad = idb.fetchSingle("SELECT HUSPOANG from ELEVHEM where ELEVHEMSNAMN =" + "'" + namn + "'");

            // konverterar Strängar till int för att kunna summera
            String talstrang = Antal.getText();
            String talstrang2 = hamtad;

            int tal1 = Integer.parseInt(talstrang);
            int tal2 = Integer.parseInt(talstrang2);

            int summa = tal1 + tal2;
            // konverterar tillbaka till Sträng för
            // sedan skicka tillbaka resultatet till FDB
            String summaStrang = Integer.toString(summa);

            idb.update("UPDATE ELEVHEM SET HUSPOANG=" + summaStrang + "where ELEVHEMSNAMN=" + "'" + namn + "'");

            // popup för att visa vad som skett så att läraren ser
            
            JOptionPane.showMessageDialog(null, svar + " har fått " + talstrang + " poäng" + " "
                    + " total " + summaStrang);
            // catch för att hindra crash
        } catch (HeadlessException | NumberFormatException | InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }

    }//GEN-LAST:event_genomförActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Antal;
    private javax.swing.JButton genomför;
    private javax.swing.JTextField hem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
